# All other configurations are set by default from ../connectomics/config/defaults.py
SYSTEM:
  NUM_GPUS: 1 #4
  NUM_CPUS: 1 #16
MODEL:
  INPUT_SIZE: [3, 112, 112]
  OUTPUT_SIZE: [3, 112, 112]
  IN_PLANES: 3
  OUT_PLANES: 3
  TARGET_OPT: ["7"]
  ARCHITECTURE: cellpose
  FILTERS: [32, 64, 128, 256]
  ACT_MODE: relu
  PAD_MODE: zeros
  LOSS_OPTION: [["WeightedMSE","WeightedBCEWithLogitsLoss"]]
  LOSS_WEIGHT: [[1.0, 1.0]]
  WEIGHT_OPT: [["1", "0"]]
  OUTPUT_ACT: [["none", "none"]]
  NORM_MODE: bn

DATASET:
  IMAGE_NAME: ../../../../datasets/cellpose/train/imgs_names.txt
  LABEL_NAME: ../../../../datasets/cellpose/train/masks_names.txt
  INPUT_PATH: ../../../../datasets/cellpose/train # dataset path
  OUTPUT_PATH: outputs/Cellpose/
  DO_2D: True
  LOAD_2D: True
  IS_ISOTROPIC: True 
  SCALE_FACTOR: [1,1]
  PAD_SIZE: [0, 0, 0]
  DROP_CHANNEL: False

SOLVER:
  # LR_SCHEDULER_NAME: WarmupCosineLR
  BASE_LR: 0.2
  ITERATION_STEP: 1
  ITERATION_SAVE: 500
  ITERATION_TOTAL: 50000
  SAMPLES_PER_BATCH: 4

AUGMENTOR:
  ELASTIC:
    ENABLED: False
  RESCALE:
    ENABLED: False


INFERENCE:
  INPUT_SIZE: [3, 112, 112]
  OUTPUT_SIZE: [3, 112, 112]
  OUTPUT_ACT: ["none"]
  IMAGE_NAME: ["000_img.png","001_img.png"] # or path to your test images
  OUTPUT_PATH: outputs/Cellpose/test
  OUTPUT_NAME: result.h5
  PAD_SIZE: [0,0,0]
  SAMPLES_PER_BATCH: 4