# All other configurations are set by default. If you want to add new config options,
# please modify ../connectomics/config/defaults.py
SYSTEM:
  NUM_GPUS: 2
  NUM_CPUS: 16
MODEL:
  INPUT_SIZE: [33, 97, 97]
  OUTPUT_SIZE: [33, 97, 97]
  IN_PLANES: 1
  OUT_PLANES: 3
  TARGET_OPT: ["2"]
  LOSS_OPTION: [["WeightedBCEWithLogitsLoss", "DiceLoss"]]
  LOSS_WEIGHT: [[1.0, 0.5]]
  WEIGHT_OPT: [["1", "0"]]
  OUTPUT_ACT: [["none", "sigmoid"]]
  NORM_MODE: sync_bn
  FILTERS: [32, 64, 96, 128, 160]
DATASET:
  IMAGE_NAME: datasets/zebrafinch/img_train.txt
  LABEL_NAME: datasets/zebrafinch/seg_train.txt
  OUTPUT_PATH: outputs/Zebrafinch/
  IS_ABSOLUTE_PATH: True
  PAD_SIZE: [4, 32, 32]
  LABEL_EROSION: 1
  DISTRIBUTED: True
SOLVER:
  LR_SCHEDULER_NAME: WarmupCosineLR
  BASE_LR: 0.04
  ITERATION_STEP: 1
  ITERATION_SAVE: 5000
  ITERATION_TOTAL: 100000
  SAMPLES_PER_BATCH: 2
INFERENCE:
  INPUT_SIZE: [33, 97, 97]
  OUTPUT_SIZE: [33, 97, 97]
  OUTPUT_ACT: ["sigmoid"]
  IMAGE_NAME: "test-input.tif" # or path to your test images
  OUTPUT_PATH: "outputs/SNEMI3D/test"
  OUTPUT_NAME: "result.h5"
  PAD_SIZE: [4, 64, 64]
  AUG_MODE: "min"
  AUG_NUM: 4
  STRIDE: [8, 128, 128]
  SAMPLES_PER_BATCH: 8
