MODEL:
  IN_PLANES: 1
  OUT_PLANES: 2
  TARGET_OPT: ['0','4-1-1']
  LOSS_OPTION:
  - - WeightedBCEWithLogitsLoss
  - - WeightedBCEWithLogitsLoss
  LOSS_WEIGHT: [[1.0], [0.4]]
  WEIGHT_OPT: [['2-10-8'], ['1-1']]
  OUTPUT_ACT: [['none'], ['none']]
INFERENCE:
  OUTPUT_ACT: ['sigmoid', 'sigmoid']
  OUTPUT_PATH: 'outputs/Parhyale_UNet_BC/test/'
DATASET:
  OUTPUT_PATH: 'outputs/Parhyale_UNet_BC/'  
