SYSTEM:
  NUM_GPUS: 2
  NUM_CPUS: 12
MODEL:
  ARCHITECTURE: 'unet_3d'
  BLOCK_TYPE: 'residual_se'
  INPUT_SIZE: [17, 193, 193]
  OUTPUT_SIZE: [17, 193, 193]
  IN_PLANES: 1
  OUT_PLANES: 2
  TARGET_OPT: ['0','4-1-1']
  LOSS_OPTION:
  - - WeightedBCEWithLogitsLoss
    - DiceLoss
  - - WeightedBCEWithLogitsLoss
    - DiceLoss
  LOSS_WEIGHT: [[1.0, 0.25], [1.0, 0.25]]
  WEIGHT_OPT: [['1', '0'],['1', '0']]
  OUTPUT_ACT: [['none', 'sigmoid'], ['none', 'sigmoid']]
  # cross-target consistency regularization
  REGU_OPT: ['FgContour']
  REGU_TARGET: [[0, 1]]
  REGU_WEIGHT: [0.1]
  NORM_MODE: 'gn'
  ACT_MODE: 'leaky_relu'
  FILTERS: [32, 64, 96, 128, 160]
DATASET:
  INPUT_PATH: 'datasets/Parhyale/train/'
  IMAGE_NAME: 'image_01.tif@image_11.tif@image_21.tif'
  LABEL_NAME: 'label_01.tif@label_11.tif@label_21.tif'
  OUTPUT_PATH: 'outputs/Parhyale_UNet_BC/'
  PAD_SIZE: [4, 32, 32]
  DATA_SCALE: [1.0, 1.0, 1.0]
  REJECT_SAMPLING:
    SIZE_THRES: 10000
    P: 1.0
  DISTRIBUTED: False
AUGMENTOR:
  CUTNOISE:
    ENABLED: False
  CUTBLUR:
    ENABLED: False
SOLVER:
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  BASE_LR: 1e-4
  ITERATION_STEP: 1
  ITERATION_SAVE: 5000
  ITERATION_TOTAL: 100000
  SAMPLES_PER_BATCH: 4
  CLIP_GRADIENTS: 
    ENABLED: True
INFERENCE:
  INPUT_SIZE: [17, 193, 193]
  OUTPUT_SIZE: [17, 193, 193]
  OUTPUT_ACT: ['sigmoid', 'sigmoid']
  INPUT_PATH: 'datasets/Parhyale/test/'
  IMAGE_NAME: 'image_41.tif@image_50.tif'
  OUTPUT_PATH: 'outputs/Parhyale_UNet_BC/test/'
  OUTPUT_NAME: 'result.h5'
  PAD_SIZE: [4, 32, 32]
  AUG_MODE: 'mean'
  AUG_NUM: 16
  STRIDE: [8, 80, 80]
  SAMPLES_PER_BATCH: 16
  OUTPUT_SCALE: [1.0, 1.0, 1.0]
