MODEL:
  IN_PLANES: 1
  OUT_PLANES: 3
  TARGET_OPT: ['0','4-1-1', '6']
  LOSS_OPTION:
  - - WeightedBCEWithLogitsLoss
    - DiceLoss
  - - WeightedBCEWithLogitsLoss
    - DiceLoss
  - WeightedMSE
  LOSS_WEIGHT: [[1.0, 0.4], [1.5, 0.5], [1.0]]
  WEIGHT_OPT: [['1', '0'], ['1', '0'], ['0']]
  OUTPUT_ACT: [['none', 'sigmoid'], ['none', 'sigmoid'], ['tanh']]
  # cross-target consistency regularization
  REGU_OPT: ['FgContour', 'ContourDT', 'FgDT']
  REGU_TARGET: [[0, 1], [1, 2], [0, 2]]
  REGU_WEIGHT: [0.5, 0.5, 0.5]
INFERENCE:
  OUTPUT_ACT: ['sigmoid', 'sigmoid', 'tanh']
DATASET:
  OUTPUT_PATH: 'outputs/Parhyale_UNet_BCD_CR/' 
  