SYSTEM:
  NUM_GPUS: 2
  NUM_CPUS: 12
MODEL:
  ARCHITECTURE: 'unet_3d'
  BLOCK_TYPE: 'residual_se'
  INPUT_SIZE: [17, 193, 193]
  OUTPUT_SIZE: [17, 193, 193]
  NORM_MODE: 'gn'
  ACT_MODE: 'leaky_relu'
  FILTERS: [32, 64, 96, 128, 160]
DATASET:
  INPUT_PATH: 'datasets/Parhyale/train/'
  IMAGE_NAME: 'image_01.tif@image_11.tif@image_21.tif'
  LABEL_NAME: 'label_01.tif@label_11.tif@label_21.tif'
  PAD_SIZE: [4, 32, 32]
  REJECT_SAMPLING:
    SIZE_THRES: 10000
    P: 1.0
  DISTRIBUTED: False
  LABEL_EROSION: 1
AUGMENTOR:
  CUTNOISE:
    ENABLED: False
  CUTBLUR:
    ENABLED: False
  MOTIONBLUR:
    ENABLED: False
SOLVER:
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  BASE_LR: 1e-3
  ITERATION_STEP: 1
  ITERATION_SAVE: 5000
  ITERATION_TOTAL: 100000
  SAMPLES_PER_BATCH: 4
  CLIP_GRADIENTS: 
    ENABLED: True
INFERENCE:
  INPUT_SIZE: [17, 193, 193]
  OUTPUT_SIZE: [17, 193, 193]
  OUTPUT_ACT: ['sigmoid', 'sigmoid']
  INPUT_PATH: 'datasets/Parhyale/test/'
  IMAGE_NAME: 'image_41.tif@image_50.tif'
  OUTPUT_PATH: 'outputs/Parhyale_UNet_BC/test/'
  OUTPUT_NAME: 'result.h5'
  PAD_SIZE: [4, 32, 32]
  AUG_MODE: 'mean'
  AUG_NUM: 16
  STRIDE: [8, 80, 80]
  SAMPLES_PER_BATCH: 16
