MODEL:
  IN_PLANES: 1
  OUT_PLANES: 2
  TARGET_OPT: ['0','4-0-1']
  LOSS_OPTION:
  - - WeightedBCEWithLogitsLoss
    - DiceLoss
  - - WeightedBCEWithLogitsLoss
    - DiceLoss
  LOSS_WEIGHT: [[1.0, 1.0], [1.0, 0.5]]
  WEIGHT_OPT: [['1', '0'], ['1-1', '0']]
  OUTPUT_ACT: [['none', 'sigmoid'], ['none', 'sigmoid']]
DATASET:
  OUTPUT_PATH: outputs/NucMM_Zebrafish_BC_debug
INFERENCE:
  OUTPUT_PATH: outputs/NucMM_Zebrafish_BC/test/
  OUTPUT_ACT: ['sigmoid', 'sigmoid']
MONITOR:
  ITERATION_NUM: [10, 10]
