SYSTEM:
  NUM_GPUS: 3
  NUM_CPUS: 12
MODEL:
  ARCHITECTURE: 'unet_3d'
  BLOCK_TYPE: 'residual_se'
  INPUT_SIZE: [97, 97, 97]
  OUTPUT_SIZE: [97, 97, 97]
  IN_PLANES: 1
  OUT_PLANES: 2
  TARGET_OPT: ['0','4-1-1']
  LOSS_OPTION: [['WeightedBCEWithLogitsLoss', 'DiceLoss'], ['WeightedBCEWithLogitsLoss', 'DiceLoss']]
  LOSS_WEIGHT: [[1.0, 0.25], [1.0, 0.25]]
  WEIGHT_OPT: [['1', '0'],['1', '0']]
  OUTPUT_ACT: [['none', 'sigmoid'], ['none', 'sigmoid']]
  NORM_MODE: 'sync_bn'
DATASET:
  INPUT_PATH: 'datasets/NucMM/Mouse/'
  IMAGE_NAME: 'im_500.h5'
  LABEL_NAME: 'seg_cb_500.h5'
  OUTPUT_PATH: 'outputs/NucMM_Mouse_BC/'
  PAD_SIZE: [16, 32, 32]
  DATA_SCALE: [1.0, 1.0, 1.0]
  REJECT_SAMPLING:
    SIZE_THRES: 1000
    P: 1.0
  DISTRIBUTED: False
AUGMENTOR:
  FLIP:
    ENABLED: True
    DO_ZTRANS: 1
  CUTBLUR:
    DOWNSAMPLE_Z: True
SOLVER:
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  BASE_LR: 0.04
  ITERATION_STEP: 1
  ITERATION_SAVE: 5000
  ITERATION_TOTAL: 100000
  SAMPLES_PER_BATCH: 2
INFERENCE:
  INPUT_SIZE: [97, 97, 97]
  OUTPUT_SIZE: [97, 97, 97]
  OUTPUT_ACT: ['sigmoid', 'sigmoid']
  IMAGE_NAME: 'im_720nm/*.png'
  OUTPUT_PATH: 'outputs/NucMM_Mouse_BC/test/'
  OUTPUT_NAME: 'result.h5'
  PAD_SIZE: [16, 32, 32]
  AUG_MODE: 'mean'
  AUG_NUM: 4
  STRIDE: [48, 48, 48]
  SAMPLES_PER_BATCH: 8
  OUTPUT_SCALE: [1.0, 1.0, 1.0]
